FROM golang:alpine AS builder

RUN apk update && apk add --no-cache git

WORKDIR /app

COPY .env .
COPY api ./api
COPY main.go .
COPY go.mod .
COPY go.sum .

RUN go mod download
RUN go build -o talkbox

FROM alpine:3.17.0 as runner

WORKDIR /app

ENV GIN_MODE=release

RUN addgroup --system --gid 1001 golang
RUN adduser --system --uid 1001 talkbox

COPY --from=builder /app/.env .
COPY --from=builder /app/talkbox .

USER talkbox

EXPOSE 8080

ENTRYPOINT [ "/app/talkbox" ]