name: Backend
run-name: Build and deploy Talkbox API
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Run unit test
        run: go test -v ./api
      - name: Build API
        run: go build -o talkbox
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: ls -la
      - run: echo "Deploy to server"