name: Backend
run-name: Run test and deploy Talkbox API
on:
  workflow_run:
    workflows: [frontend]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Run unit test
        run: go test -v ./api

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    env: 
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only --config fly.api.toml