name: Build and deploy
run-name: Run test and deploy Talkbox web app
on:
  push:
    branches:
      - main
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Run unit test
        run: go test -v ./api

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
      - name: Run lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

  deploy:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only --config fly.toml